---
- name: Update the package list
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist

- name: Remove unnecessary packages
  ansible.builtin.apt:
    autoremove: yes
